// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhFD8VyNb2qGQ9k8Vbapcpl0bYbQ6Jngs',
    appId: '1:684946722252:web:63381757a34b3e019d6169',
    messagingSenderId: '684946722252',
    projectId: 'skylancer-91511',
    authDomain: 'skylancer-91511.firebaseapp.com',
    storageBucket: 'skylancer-91511.appspot.com',
    measurementId: 'G-QR1Y1G2D72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVJa0FkG4Pa-omQ2I60m7eHbhxG15lyHQ',
    appId: '1:684946722252:android:cc23e4480b46359e9d6169',
    messagingSenderId: '684946722252',
    projectId: 'skylancer-91511',
    storageBucket: 'skylancer-91511.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaXzGo48YBEHzfRkXEhe-zlIXxcJt88iw',
    appId: '1:684946722252:ios:246513590116a2bb9d6169',
    messagingSenderId: '684946722252',
    projectId: 'skylancer-91511',
    storageBucket: 'skylancer-91511.appspot.com',
    androidClientId: '684946722252-l31h0mcfk5i831o40nmsq572ai6jg4je.apps.googleusercontent.com',
    iosClientId: '684946722252-halr70dsve4dei4brfq6c0sedtmtol77.apps.googleusercontent.com',
    iosBundleId: 'com.selmanaslan.skylancer.skylancer',
  );
}
